import os
from dotenv import load_dotenv
from langchain.agents import AgentExecutor, create_tool_calling_agent
from langchain.memory import ConversationBufferMemory
from langchain_core.prompts import ChatPromptTemplate
from langchain_google_genai import ChatGoogleGenerativeAI

from .logger import Logger
from ..api.schemas import Plan


load_dotenv()
llm = ChatGoogleGenerativeAI(model="gemini-2.5-pro", api_key=os.environ.get("GOOGLE_API_KEY"))

class KawanAgent:
    def __init__(self, tools, plan: Plan, max_iterations=100):
        self.tools = tools
        self.max_iterations = max_iterations
        self.model = llm
        self.plan = plan
        self.persona = plan.persona
        self.logger = Logger("kawan_agent").get_logger()

        itinerary_summary = ""
        if self.plan.itinerary:
            itinerary_summary = "\n\nHere is the current itinerary:\n" + "\n".join(
                [f"Stop {s.stop}: {s.place_details.get('name', 'N/A')} at {s.time} - {s.narrative}" for s in self.plan.itinerary]
            )

        system_prompt = f"""
        You are {self.persona.name}, a {self.persona.tone} tour guide.
        Your backstory: {self.persona.backstory}
        This is current plan, generated by an AI:
        {itinerary_summary}
        Look at the conversation history, would you want to reply user message, propose a new draft plan, or confirm a draft plan?

        This decides which of the following tools to use in your **LAST STEP**:
        - `propose_draft_plan`: Use this when the user asks to create or change the itinerary.
        - `message_user`: Use this for all other conversational purposes, like asking for clarification or chatting with the user.

        To propose a draft plan, you should use other tools to assist you gain context to draft the plan.
        To message user, you might need to use other tools.
        """

        self.memory = ConversationBufferMemory(memory_key="chat_history", return_messages=True)
        # - `confirm_draft_plan`: Use this ONLY when the user explicitly confirms a proposed plan.
        # - `message_user`: Use this for all other conversational purposes, like asking for clarification or chatting with the user.
        # Load conversation history
        if self.plan.conversation_history:
            for message in self.plan.conversation_history:
                if message.role == "human":
                    self.memory.chat_memory.add_user_message(message.content)
                elif message.role == "ai":
                    self.memory.chat_memory.add_ai_message(message.content)

        prompt = ChatPromptTemplate.from_messages([
            ("system", system_prompt),
            ("placeholder", "{chat_history}"),
            ("human", "{input}"),
            ("placeholder", "{agent_scratchpad}"),
        ])

        agent = create_tool_calling_agent(self.model, self.tools, prompt)
        self.executor = AgentExecutor(
            agent=agent,
            tools=self.tools,
            memory=self.memory,
            max_iterations=self.max_iterations,
            verbose=True,
            handle_parsing_errors=True,
            return_intermediate_steps=True,
        )

    def run(self, human_prompt: str):
        self.logger.info(f"Human prompt: {human_prompt}")
        try:
            response = self.executor.invoke({"input": human_prompt})
            self.logger.info(f"Agent response: {response}")

            agent_response_text = response.get("output")

            # Check if a tool was called and determine the action
            if "intermediate_steps" in response and response["intermediate_steps"]:
                last_step = response["intermediate_steps"][-1]
                tool_name = last_step[0].tool
                tool_output = last_step[1]
                self.logger.info(f"Tool '{tool_name}' called with output: {tool_output}")

                if tool_name == "propose_draft_plan":
                    return {
                        "action": "propose_draft_plan",
                        "payload": tool_output,
                        "message": agent_response_text
                    }
                elif tool_name == "message_user":
                    return {
                        "action": "message_user",
                        "payload": {},
                        "message": tool_output
                    }

            # Default to message_user action if no specific tool was called in the last step
            self.logger.info(f"No specific action tool called in the last step. Returning conversational output.")
            return {
                "action": "message_user",
                "payload": {},
                "message": agent_response_text
            }

        except Exception as e:
            self.logger.error("Exception in agent run", exc_info=True)
            return {
                "action": "error",
                "payload": {"error_message": str(e)},
                "message": "I'm sorry, but an unexpected error occurred. Please try again."
            }

class PlannerAgent:
    def __init__(self, tools, max_iterations=100):
        self.tools = tools
        self.max_iterations = max_iterations
        self.model = llm
        self.logger = Logger("planner_agent").get_logger()

    def run(self, human_prompt: str, system_prompt: str):
        self.logger.info(f"Human prompt: {human_prompt}")

        # Override the system prompt to be more specific for the planner agent
        
        prompt = ChatPromptTemplate.from_messages([
            ("system", system_prompt),
            ("human", "{input}"),
            ("placeholder", "{agent_scratchpad}"),
        ])

        agent = create_tool_calling_agent(self.model, self.tools, prompt)
        executor = AgentExecutor(
            agent=agent,
            tools=self.tools,
            max_iterations=self.max_iterations,
            verbose=True,
            handle_parsing_errors=True,
            return_intermediate_steps=True,  # Return intermediate steps
        )

        try:
            response = executor.invoke({"input": human_prompt})
            self.logger.info(f"Agent response: {response}")

            # If a tool was called, return the output of the last tool call
            if "intermediate_steps" in response and response["intermediate_steps"]:
                # The last step is a tuple of (AgentAction, observation)
                last_tool_output = response["intermediate_steps"][-1][1]
                self.logger.info(f"Last tool output: {last_tool_output}")
                return last_tool_output
            
            # Otherwise, return the conversational output
            self.logger.info(f"No intermediate steps found. Returning conversational output: {response.get('output')}")
            return response.get("output")

        except Exception as e:
            self.logger.error("Exception in agent run", exc_info=True)
            return f"An error occurred: {e}"
