from pydantic import BaseModel, Field
from enum import Enum
from typing import List, Optional, Union

class SearchDepth(str, Enum):
    BASIC = "basic"
    ADVANCED = "advanced"

class Topic(str, Enum):
    GENERAL = "general"
    NEWS = "news"
    FINANCE = "finance"

class InternetSearch(BaseModel):
    query: str = Field(..., description="The query to run a search on.")
    auto_parameters: bool = Field(False, description="When auto_parameters is enabled, Tavily automatically configures search parameters based on your query’s content and intent.")
    search_depth: SearchDepth = Field(SearchDepth.ADVANCED, description='The depth of the search. It can be "basic" or "advanced".')
    topic: Topic = Field(Topic.GENERAL, description='The category of the search. Determines which agent will be used. Supported values are "general", "news" and "finance".')
    days: Optional[int] = Field(7, description='The number of days back from the current date to include in the results ( publish date ). Available only when using the "news" topic.')
    time_range: Optional[str] = Field(None, description='The time range back from the current date ( publish date ). Accepted values include "day", "week", "month", "year" or shorthand values "d", "w", "m", "y".')
    start_date: Optional[str] = Field(None, description='Will return all results after the specified start date ( publish date ). Required to be written in the format YYYY-MM-DD')
    end_date: Optional[str] = Field(None, description='Will return all results before the specified end date ( publish date ). Required to be written in the format YYYY-MM-DD.')
    max_results: Optional[int] = Field(5, description="The maximum number of search results to return. It must be between 0 and 20.")
    chunks_per_source: Optional[int] = Field(3, description='Chunks are short content snippets (maximum 500 characters each) pulled directly from the source. Use chunks_per_source to define the maximum number of relevant chunks returned per source and to control the content length. Chunks will appear in the content field as: <chunk 1> [...] <chunk 2> [...] <chunk 3>. Available only when search_depth is "advanced".')
    include_images: bool = Field(False, description="Include a list of query-related images in the response.")
    include_image_descriptions: bool = Field(False, description="Include a list of query-related images and their descriptions in the response.")
    include_answer: Union[bool, str] = Field(False, description='Include an answer to the query generated by an LLM based on search results. A "basic" (or True) answer is quick but less detailed; an "advanced" answer is more detailed.')
    include_raw_content: Union[bool, str] = Field(False, description='Include the cleaned and parsed HTML content of each search result. "markdown" or True returns search result content in markdown format. "text" returns the plain text from the results and may increase latency.')
    include_domains: List[str] = Field([], description="A list of domains to specifically include in the search results. Maximum 300 domains.")
    exclude_domains: List[str] = Field([], description="A list of domains to specifically exclude from the search results. Maximum 150 domains.")
    country: Optional[str] = Field(None, description="Boost search results from a specific country. This will prioritize content from the selected country in the search results. Available only if topic is general.")
    timeout: int = Field(60, description="A timeout to be used in requests to the Tavily API.")
    include_favicon: bool = Field(False, description="Whether to include the favicon URL for each result.")

class Result(BaseModel):
    title: str
    url: str
    content: str
    score: float
    raw_content: Optional[str] = None
    published_date: Optional[str] = None
    favicon: Optional[str] = None

class ImageResult(BaseModel):
    url: str
    description: str

class SearchResponse(BaseModel):
    results: List[Result]
    query: str
    response_time: float
    answer: Optional[str] = None
    images: Optional[Union[List[str], List[ImageResult]]] = None
    request_id: str